(()=>{function ia(a,c){return c?a.publicKey===c.publicKey&&a.i===c.i:!0}function H(a,c){for(const b of c.splice(0))a(b[0],...b.slice(1))}function x(){var a,c;const b=document.currentScript;var d=(null==b?0:b.src)?new URL(b.src,location.href):new URL("/tag.js",location.href);const e=(null==b?0:b.dataset.endpoint)?(new URL(b.dataset.endpoint,location.href)).toString():(new URL("/e",d)).toString();d=(null==b?0:b.dataset.config)?(new URL(b.dataset.config,location.href)).toString():(new URL("/config",
d)).toString();return{publicKey:null!=(c=null!=(a=null==b?void 0:b.dataset.key)?a:window.TrackrrKey)?c:"",i:null==b?void 0:b.dataset.zone,endpoint:e,l:d}}function ja(){var a=Date.now();const c=P("trackrr_vid",`v_${t()}`);a=C(a);const b=`p_${t()}`;return{B:c.value,sessionId:a.sessionId,o:b,m:c.g}}function P(a,c){try{const b=window.localStorage.getItem(a);if(b)return{value:b,g:!1};window.localStorage.setItem(a,c);return{value:c,g:!0}}catch(b){return{value:c,g:!0}}}function C(a){try{const c=window.sessionStorage.getItem("trackrr_sid"),
b=c?JSON.parse(c):null;if(u(b)&&"string"===typeof b.sessionId&&18E5>a-Number(b.lastSeen))return window.sessionStorage.setItem("trackrr_sid",JSON.stringify({sessionId:b.sessionId,lastSeen:a})),{sessionId:b.sessionId};const d={sessionId:`s_${t()}`,lastSeen:a};window.sessionStorage.setItem("trackrr_sid",JSON.stringify(d));return{sessionId:d.sessionId}}catch(c){return{sessionId:`s_${t()}`}}}function l(a,c,b={}){var d=null!=m?m:x(),e=d.publicKey;if(e){var f=d.i;a={id:`evt_${t()}_${Date.now().toString(36)}`,
type:a,time:(new Date).toISOString(),name:c,properties:b};var g,k,p,h;b=new URL(location.href);const I=document.referrer||"";var y=window.trackrr;c=location.hostname;var v=location.hostname;var w=v.toLowerCase().split(".").filter(Boolean);2>=w.length?w=v.toLowerCase():(v=w.slice(-2).join("."),w=["co.uk","com.au","co.nz"].includes(v)&&3<=w.length?w.slice(-3).join("."):v);v=`${location.pathname}${location.search}`;var ka=b.toString();if(I)try{var J=(new URL(I)).hostname.toLowerCase()}catch(K){J=""}else J=
"";var la=document.title,ma=navigator.language,na=(new Intl.DateTimeFormat).resolvedOptions().timeZone,oa={width:window.innerWidth,height:window.innerHeight},pa=navigator.userAgent,qa=null!=(g=null==q?void 0:q.B)?g:P("trackrr_vid",`v_${t()}`).value;g=C(Date.now()).sessionId;var ra=null!=(k=null==q?void 0:q.o)?k:`p_${Date.now().toString(36)}`;k="denied"===(null==(p=y.consent)?void 0:p.analytics);p=null!=(h=y.consent)?h:{analytics:"unknown",ads:"unknown"};h={};for(const K of["source","medium","campaign",
"term","content"])(y=b.searchParams.get(`utm_${K}`))&&(h[K]=y);e={publicKey:e,zoneKey:f,event:a,context:{host:c,rootDomain:w,path:v,url:ka,referrer:I,referrerHost:J,title:la,language:ma,timezone:na,viewport:oa,userAgent:pa,visitorId:qa,sessionId:g,pageId:ra,reducedData:k,consent:p,utm:h}};d=d.endpoint;var Q;f=window.trackrr;f.pending=null!=(Q=f.pending)?Q:[];f.pending.push({endpoint:d,j:e});sa()}}function sa(){D||(D=!0,Promise.resolve().then(()=>{D=!1;R()}))}function R(){var a,c;D=!1;var b=null!=
(c=null==(a=window.trackrr.pending)?void 0:a.splice(0))?c:[];a=new Map;for(var d of b)(b=a.get(d.endpoint))?b.push(d.j):a.set(d.endpoint,[d.j]);for(const [e,f]of a){d=[];for(const g of f)b=[...d,g],a=JSON.stringify(1===b.length?b[0]:{events:b}),0<d.length&&(25<b.length||49152<a.length)?(S(e,d),d=[g]):d=b;S(e,d)}}function S(a,c){var b;if(0!==c.length){c=JSON.stringify(1===c.length?c[0]:{events:c});var d=new Blob([c],{type:"application/json"});(null==(b=navigator.sendBeacon)?0:b.call(navigator,a,d))||
fetch(a,{method:"POST",body:c,headers:{"content-type":"application/json"},keepalive:!0,credentials:"omit"}).catch(()=>{})}}function ta(){const a=history.pushState,c=history.replaceState,b=()=>{var d;const e=location.pathname+location.search;e!==L&&(L=e,null==(d=window.trackrr)||d.call(window,"page"))};history.pushState=function(...d){d=a.apply(this,d);window.setTimeout(b,0);return d};history.replaceState=function(...d){d=c.apply(this,d);window.setTimeout(b,0);return d};window.addEventListener("popstate",
b)}function ua(){var a;window.addEventListener("focus",M);window.addEventListener("blur",()=>E("blur"));window.addEventListener("pagehide",()=>{var b;E("pagehide");null==(b=window.trackrr)||b.call(window,"flush")});const c=document;null==(a=c.addEventListener)||a.call(c,"visibilitychange",()=>{"hidden"===c.visibilityState?E("visibility_hidden"):M()})}function M(){F=Date.now()}function E(a){if(F){var c=Date.now(),b=c-F;F=c;1E3>b||l("user_engagement","user_engagement",{engagement_time_msec:b,engagementReason:a})}}
function va(){const a=null!=m?m:x();if(a.publicKey){var c=new URL(a.l);c.searchParams.set("key",a.publicKey);fetch(c.toString(),{method:"GET",credentials:"omit",keepalive:!0}).then(b=>b.ok?b.json():void 0).then(b=>{var d;if(b){var e=u(b.tag)?b.tag:b.siteGroup;u(e)&&(n={publicKey:String(null!=(d=e.publicKey)?d:a.publicKey),h:"string"===typeof e.popFrequencyMode?e.popFrequencyMode:void 0,u:!0===e.popEnabled,s:"string"===typeof e.popDestinationUrl?e.popDestinationUrl:void 0,v:!0===e.videoFlyoutEnabled,
A:"string"===typeof e.videoFlyoutUrl?e.videoFlyoutUrl:void 0},T||(T=!0,N()),U());Array.isArray(b.partnerScripts)&&(V=b.partnerScripts.filter(f=>u(f)&&!0===f.enabled));z("after_pageview",void 0)}}).catch(()=>{})}}function N(){void 0!==G&&(window.clearTimeout(G),G=void 0);if(W()){var a=X();if(0===a){if(!A){a=document.createElement("div");a.dataset.trackrrPopTrigger="fullscreen";a.setAttribute("aria-hidden","true");a.addEventListener("click",wa,!0);var c=a.style;c.position="fixed";c.inset="0";c.width=
"100vw";c.height="100vh";c.zIndex="2147483646";c.background="transparent";c.cursor="inherit";c.pointerEvents="auto";c.touchAction="manipulation";(document.body||document.documentElement).appendChild(a);A=a}}else Y(),"number"===typeof a&&(G=window.setTimeout(N,a))}else Y()}function Y(){A&&(A.remove(),A=void 0)}function wa(a){Z()&&(a.preventDefault(),a.stopPropagation(),a.stopImmediatePropagation());N()}function Z(a={}){var c,b,d;const e=W(null!=(c=a.requirePopEnabled)?c:!0);c=!0===a.ignoreFrequencyCap;
if(!e||!c&&0!==X())return!1;if(!c){var f,g=null!=m?m:x(),k={sessionId:null!=(f=null==q?void 0:q.sessionId)?f:C(Date.now()).sessionId,lastAttemptedAt:Date.now()};f=`trackrr_pop_state_${g.publicKey}`;aa[f]=k;try{window.localStorage.setItem(f,JSON.stringify(k))}catch(h){}}g=null!=m?m:x();f=`pop_${t()}_${Date.now().toString(36)}`;k=location.hostname.toLowerCase();g=g.publicKey;try{const h=new URL(e,location.href);h.searchParams.set("ref",g);h.searchParams.set("trk_pop_id",f);h.searchParams.set("trk_src",
k);var p=h.toString()}catch(h){p=e}a={destinationUrl:e,attributedDestinationUrl:p,popId:f,sourceHost:k,trigger:"click",triggerSurface:null!=(b=a.triggerSurface)?b:"fullscreen_overlay",frequencyMode:c?"uncapped":null!=(d=null==n?void 0:n.h)?d:"session_or_15_minutes",referrerPolicy:"noreferrer",openDetection:"noreferrer_unobservable"};l("pop_eligible","pop_eligible",a);z("after_pop_eligible",void 0);l("pop_attempt","pop_attempt",a);b=!1;try{const h=window.open(p,"_blank","noopener,noreferrer");b=!0;
h&&(h.opener=null);try{window.focus()}catch(y){}}catch(h){b=!1}b?l("pop_opened","pop_opened",a):l("pop_blocked","pop_blocked",a);return!0}function W(a=!0){if(n&&(!a||n.u)&&"observe_only"!==n.h&&(a=n.s))try{const c=new URL(a,location.href);return"http:"!==c.protocol&&"https:"!==c.protocol?void 0:c.toString()}catch(c){}}function X(){var a,c;const b=null!=m?m:x(),d=null!=(a=null==q?void 0:q.sessionId)?a:C(Date.now()).sessionId;a:{var e;a=`trackrr_pop_state_${b.publicKey}`;try{const g=window.localStorage.getItem(a),
k=g?JSON.parse(g):void 0;if(u(k)){var f={sessionId:"string"===typeof k.sessionId?k.sessionId:void 0,lastAttemptedAt:"number"===typeof k.lastAttemptedAt?k.lastAttemptedAt:void 0};break a}}catch(g){f=null!=(e=aa[a])?e:{};break a}f={}}if(!f.lastAttemptedAt)return 0;e=null!=(c=null==n?void 0:n.h)?c:"session_or_15_minutes";if("once_per_session"===e)return f.sessionId!==d?0:void 0;c=Date.now()-f.lastAttemptedAt;return"every_15_minutes"===e?Math.max(9E5-c,0):f.sessionId!==d?0:Math.max(9E5-c,0)}function U(){a:{if(!0===
(null==n?void 0:n.v)){var a=n.A||"https://abdct.com/media/";try{const b=new URL(a,location.href);var c="http:"!==b.protocol&&"https:"!==b.protocol?void 0:b.toString();break a}catch(b){}}c=void 0}a=`${location.pathname}${location.search}`;c&&ba!==a?xa(c):ca()}function xa(a){if(r)B&&B.src!==a&&(B.src=a);else{var c=document.createElement("div");c.dataset.trackrrVideoFlyout="bottom_left";c.setAttribute("role","dialog");c.setAttribute("aria-label","Video");var b=c.style;b.position="fixed";b.left="16px";
b.bottom="16px";b.width="400px";b.maxWidth="calc(100vw - 32px)";b.aspectRatio="16 / 9";b.zIndex="2147483647";b.background="#000";b.boxShadow="0 18px 50px rgba(0, 0, 0, 0.35)";b.overflow="visible";b.transform="translate(-18px, 28px)";b.opacity="0";b.transition="transform 220ms ease, opacity 220ms ease";b=document.createElement("iframe");b.src=a;b.width="400";b.height="225";b.C="eager";b.scrolling="no";b.referrerPolicy="no-referrer";b.allow="autoplay; fullscreen; encrypted-media";b.setAttribute("allowfullscreen",
"true");a=b.style;a.width="100%";a.height="100%";a.border="0";a.overflow="hidden";a.display="block";a=document.createElement("button");a.type="button";a.textContent="X";a.setAttribute("aria-label","Close video");a.addEventListener("click",ya,!0);var d=a.style;d.position="absolute";d.right="-10px";d.top="-10px";d.width="28px";d.height="28px";d.border="0";d.borderRadius="999px";d.background="#111827";d.color="#ffffff";d.font="600 13px/28px Arial, sans-serif";d.textAlign="center";d.cursor="pointer";
d.boxShadow="0 8px 20px rgba(0, 0, 0, 0.35)";d.padding="0";c.appendChild(b);c.appendChild(a);(document.body||document.documentElement).appendChild(c);r=c;B=b;window.setTimeout(()=>{r&&(r.style.transform="translate(0, 0)",r.style.opacity="1")},0)}}function ya(a){a.preventDefault();a.stopPropagation();a.stopImmediatePropagation();ba=`${location.pathname}${location.search}`;Z({triggerSurface:"video_flyout_close",requirePopEnabled:!1,ignoreFrequencyCap:!0});ca()}function ca(){r&&(r.remove(),B=r=void 0)}
function z(a,c){for(const d of V)if(d.loadMode===a&&!(c&&d.name!==c&&d.id!==c||da.has(d.id))){da.add(d.id);if(d.scriptUrl){var b=document.createElement("script");b.async=!0;b.src=d.scriptUrl;b.dataset.trackrrPartner=d.id;ea(d).appendChild(b)}d.inlineScript&&(b=document.createElement("script"),b.text=d.inlineScript,b.dataset.trackrrPartner=d.id,ea(d).appendChild(b))}}function ea(a){return"head"===a.placement?document.head:document.body||document.documentElement}function fa(a){var c;return null!=(c=
{eligible:"pop_eligible",capped:"pop_frequency_capped",frequency_capped:"pop_frequency_capped",attempt:"pop_attempt",attempted:"pop_attempt",blocked:"pop_blocked",opened:"pop_opened",shown:"pop_opened",redirect_started:"pop_redirect_started",redirect_completed:"pop_redirect_completed"}[a.replace(/^pop_/,"")])?c:"pop_attempt"}function O(a){return u(a)?a:{}}function u(a){return"object"===typeof a&&null!==a&&!Array.isArray(a)}function ha(a){return"granted"===a||"denied"===a?a:"unknown"}function t(){if(crypto.randomUUID)return crypto.randomUUID().replace(/-/g,
"");const a=new Uint8Array(16);crypto.getRandomValues(a);return Array.from(a,c=>c.toString(16).padStart(2,"0")).join("")}var m,q,n,V=[],da=new Set,T=!1,A,G,r,B,ba="",D=!1,aa={},L="",F=0;(function(){var a=x();const c=window.trackrr,b=Array.isArray(null==c?void 0:c.q)?c.q:[],d=window.__trackrr,e="function"===typeof(null==d?void 0:d.api)?d.api:void 0;!0===(null==d?void 0:d.loaded)&&e&&ia(a,d.config)?(window.trackrr=e,H(e,b)):"function"!==typeof c||!0!==c.loaded||d?(m=a,q=ja(),L=location.pathname+location.search,
a=function(f,...g){var k,p;if("consent"===f){if(g=g[0],u(g)){var h=window.trackrr;h.consent={analytics:ha(g.analytics),ads:ha(g.ads)};"granted"!==h.consent.analytics&&"granted"!==h.consent.ads||z("after_consent",void 0)}}else if("identify"===f){if(g=g[0],!("string"!==typeof g||1>g.length))try{window.localStorage.setItem("trackrr_vid",`u_${g}`)}catch(y){}}else"flush"===f?R():"partner"===f?"load"===String(null!=(k=g[0])?k:"load")&&z("manual","string"===typeof g[1]?g[1]:void 0):"page"===f?(E("page_change"),
l("page_view","page_view",O(g[0])),z("after_pageview",void 0),U()):"event"===f?l("custom_event",String(null!=(p=g[0])?p:"custom_event"),O(g[1])):"pop"===f&&(f=String(null!=(h=g[0])?h:"attempt"),l(fa(f),`pop_${f}`,O(g[1])),"pop_eligible"===fa(f)&&z("after_pop_eligible",void 0))},a.q=[],a.loaded=!0,window.trackrr=a,window.__trackrr={api:a,config:m,loaded:!0},M(),l("tag_loaded","tag_loaded"),q.m&&l("first_visit","first_visit"),l("session_start","session_start"),l("page_view","page_view"),va(),ta(),ua(),
H(a,b)):(window.__trackrr={api:c,config:a,loaded:!0},H(c,b))})()})();
